name: Run tests
on: [push]
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install cmake openmpi-bin openmpi-common libopenmpi-dev cmake libmetis-dev libeigen3-dev git
        git clone https://github.com/KarypisLab/GKlib.git
        cd GKlib
        make
        make install
    - name: Build ParGibbs (with MPI)
      run: |
        mkdir build
        cmake -S . -B build -DUSE_METIS=True -DMETIS_ROOT=/home/runner/local/
        cmake --build build
    - name: Run tests (with MPI)
      run: ./build/tests/tests
    - name: Build ParGibbs (with FakeMPI)
      run: |
        rm -rf build
        mkdir build
        cmake -S . -B build -DUSE_MPI=False -DUSE_METIS=True -DMETIS_ROOT=/home/runner/local/
        cmake --build build
    - name: Run tests (with FakeMPI)
      run: ./build/tests/tests
  
