name: ubuntu
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt update
          sudo apt install -y cmake mpich intel-oneapi-mkl

      - name: Cache PETSc
        id: cache-petsc
        uses: actions/cache@v4
        with: 
          path: ${{github.workspace}}/petsc
          key: ${{runner.os}}-petsc1

      - name: Build PETSc
        if: steps.cache-petsc.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 -b release https://gitlab.com/petsc/petsc.git petsc
          cd petsc
          ./configure --with-debugging=no --with-fortran-bindings=0 --with-blas-lapack-dir=/opt/intel/mkl/lib/intel64 --with-mkl_cpardiso COPTFLAGS="-O3 -march=native" CXXOPTFLAGS="-O3 -march=native"
          make PETSC_DIR=${GITHUB_WORKSPACE}/petsc PETSC_ARCH=arch-linux-c-opt all

      - name: Build ParMGMC
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpic++ -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/petsc/arch-linux-c-opt
          make

      - name: Run serial tests
        run: ${GITHUB_WORKSPACE}/build/tests/tests [seq]

      - name: Run parallel tests
        run: mpirun -np 4 ${GITHUB_WORKSPACE}/build/tests/tests [mpi]
        
  
