name: ubuntu
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake mpich
      - name: Build PETSc
        run: |
          cd $HOME
          git clone --depth 1 -b release https://gitlab.com/petsc/petsc.git petsc
          cd petsc
          ./configure --with-debugging=no --with-fortran-bindings=0 COPTFLAGS="-O3 -march=native" CXXOPTFLAGS="-O3 -march=native"
          make PETSC_DIR=$HOME/petsc PETSC_ARCH=arch-linux-c-opt all
      - name: Build ParMGMC
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpic++ -DCMAKE_PREFIX_PATH=$HOME/petsc
          make
      - name: Run tests
        run: ./tests/tests
  
