name: ubuntu
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake petsc-dev 
      - name: Build ParMGMC
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpic++ -DCMAKE_PREFIX_PATH=/usr/lib/petsc
          make
      - name: Run tests
        run: ./tests/tests
  
